version: "3.8"

services:
  app:    # Spring Boot 애플리케이션 서비스
    build:
      context: .
      dockerfile: Dockerfile
      target: development    # 개발 환경용 스테이지 사용
    ports:
      - "8080:8080"         # API 서버 포트
    environment:
      # 데이터베이스 설정
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/jpa_tutorial
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=postgres
      # Spring 설정
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
      - SPRING_SQL_INIT_MODE=always
      - SPRING_JPA_DEFER_DATASOURCE_INITIALIZATION=true
      # DevTools 설정
      # - SPRING_DEVTOOLS_RESTART_ENABLED=true
      # - SPRING_DEVTOOLS_LIVERELOAD_ENABLED=true
    volumes:
      - .:/app
      - gradle_cache:/root/.gradle
      - /dev/null:/app/gradle.properties
    depends_on:
      - db

  db:    # PostgreSQL 데이터베이스 서비스
    image: postgres:14
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=jpa_tutorial
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:    # 데이터베이스 데이터 영속성
  gradle_cache:     # Gradle 빌드 캐시